FROM maven:3.9-eclipse-temurin-25 AS builder

WORKDIR /app

COPY Visons/pom.xml .
COPY Visons/src ./src

RUN mvn clean package -DskipTests

FROM eclipse-temurin:25-jre-alpine

WORKDIR /app

RUN apk add --no-cache curl

COPY --from=builder /app/target/*.jar app.jar

ENV PORT=8080

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
