# docker compose -f docker-compose-db.yml up -d
# docker compose -f docker-compose-db.yml down

version: '3.8'

services:
  mssql-server:
    image: diego5621/sql-server-visons:2022
    container_name: sqlserver-db-diego
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Admin12345!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - visons-network

volumes:
  mssql_data:
    driver: local

# CREAR UNA RED EN ESTE COMPOSE PARA QUE SEA COMPARTIDA
networks:
  visons-network:
    name: visons-network   # red compartida, visible desde ambos compose
    driver: bridge
